Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pymc as pm
import arviz as az
from ghgf.pymc import HGFDistribution
from ghgf.response import gaussian_surprise
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[15], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpymc[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpm[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01marviz[39;00m [38;5;28;01mas[39;00m [38;5;21;01maz[39;00m
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mghgf[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpymc[39;00m [38;5;28;01mimport[39;00m HGFDistribution
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mghgf[39;00m[38;5;21;01m.[39;00m[38;5;21;01mresponse[39;00m [38;5;28;01mimport[39;00m gaussian_surprise

File [0;32m/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/ghgf/pymc.py:5[0m
[1;32m      1[0m [38;5;66;03m# Author: Nicolas Legrand <nicolas.legrand@cfin.au.dk>[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mimport[39;00m Callable, Dict, Optional, Tuple, List
[0;32m----> 5[0m [38;5;28;01mimport[39;00m [38;5;21;01maesara[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtensor[39;00m [38;5;28;01mas[39;00m [38;5;21;01mat[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mjax[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mjnp[39;00m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

[0;31mModuleNotFoundError[0m: No module named 'aesara'
ModuleNotFoundError: No module named 'aesara'

